services:
  storer-service:
    build: .
    environment:
      - SERVICE_PORT:9952
      - API_VERSION_LTS=1.1
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    volumes:
      - ./src:/usr/src/app
  mongodb:
    image: mongo:7.0.4
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
