services:
  storer-service:
    build: .
    environment:
      - SERVICE_PORT:9952
      - API_VERSION_LTS=0
    ports:
      - "9952:9952"
    volumes:
      - .:/usr/src/omnidata_storer_service
  mongodb:
    image: mongo:7.0.4
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
