services:
  storer-service:
    build: .
    ports:
      - "9952:9952"
    volumes:
      - ./src:/usr/src/app
  mongodb:
    image: mongo:7.0.4
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
