openapi: 3.0.2
info:
  title: Omnidata Storer Service
  version: 0.1.1
paths:
  /storer/users:
    post:
      summary: Store a new user
      responses:
        '201':
          description: User Stored
    get:
      summary: Get a user list  
      responses:
        '200':
          description: User list
  /storer/users/{user_id}:
    get:
      summary: Get a specific user
      responses:
        '200':
          description: a especific user
  /storer/data-products:
    post:
      summary: Store a new Data Product
      responses:
        '201':
          description: Data Product stored
  /storer/data-products/{data_product_id}:
    patch:
      summary: Update the qlik app layout id of a Data Product
      parameters:
        - name: data_product_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Qlik app layout id updated
  /storer/data-products/{data_product_id}/data-locations:
    get:
      summary: Get all data-locations from determinated data product
      parameters:
        - name: data_product_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de conexões de dados
  /storer/data-products/{data_product_id}/data-locations/qlik/app-layout-id:
    patch:
      summary: Update the qlik app layout id reference of a Data Product
      parameters:
        - name: data_product_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: qlik app layout script updated
  /storer/data-products/{data_product_id}/data-locations/qlik/app/app-layout-script:
    patch:
      summary: Update the qlik app layout script reference of a Data Product
      parameters:
        - name: data_product_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: qlik layout app script updated

  /storer/data-products/{data_product_id}/data-locations/apacheDrill/catalog-reference:
    patch:
      summary: Update the Apache Drill catalog reference of a Data Product
      parameters:
        - name: data_product_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Apache Drill catalog reference updated
  /storer/data-products/{data_product_id}/job:
    post:
      summary: Create a job for a Data Product
      parameters:
        - name: data_product_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Job created
  /storer/data-products/{data_product_id}/job/{job_id}:
    put:
      summary: Update a specific job information of a Data Product
      parameters:
        - name: data_product_id
          in: path
          required: true
          schema:
            type: string
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Job updated