openapi: 3.0.2
info:
  title: Omnidata Storer Service
  version: 0.1.2
paths:
  /storer/users:
    post:
      summary: Store a new user
      requestBody:
        required: true
        content:
          application/json:
              schema:
                type: object
                properties:
                  user_name:
                    type: string
                    description: The user full name
                    example: Wederson Domingues
                  user_externalId:
                    type: string
                    description: The user AD id
                    example: gabriela\wederson.domingues
      responses:
        '201':
          description: User Stored
        '500':
          description: Error in database
        '400':
          description: Error in parameters
    get:
      summary: Get a user list  
      responses:
        '200':
          description: User list
  /storer/users/{user_id}:
    get:
      summary: Get a specific user by user_id
      parameters:
        - name: user_id
          in: path
          required: true
          example: 65758e91c5d4577589e699f5
          schema:
            type: string
      responses:
        '200':
          description: a especific user
  /storer/data-products:
    post:
      summary: Store a new Data Product
      requestBody:
        required: true
        content:
          application/json:
              schema:
                type: object
                properties:
                  dataProduct_name:
                    type: string
                    description: The data product name.
                    example: Etiquetas Amarelas
                  dataProduct_dominium:
                    type: string
                    description: Data product dominium
                    example: CP
                  user_owner:
                    type: string
                    description: Data product user ID
                    example: 6575960856f33537b005f9aa
      responses:
        '201':
          description: Data Product stored
    get:
      summary: Get data product list
      responses:
        '200':
          description: Sucessful
  /storer/data-products/{data_product_id}:
    get:
      summary: Get a especific data product
      parameters:
        - name: data_product_id
          in: path
          required: true
          example: 65758e91c5d4577589e699f5
          schema:
            type: string
      responses:
        '200':
          description: a especific user
    patch:
      summary: Update the qlik app layout id of a Data Product
      parameters:
        - name: data_product_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Qlik app layout id updated
  /storer/data-products/{data_product_id}/data-locations:
    get:
      summary: Get all data-locations from determinated data product
      parameters:
        - name: data_product_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de conexões de dados
  /storer/data-products/{data_product_id}/data-locations/qlik/app-layout-id:
    patch:
      summary: Update the qlik app layout id reference of a Data Product
      parameters:
        - name: data_product_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: qlik app layout script updated
  /storer/data-products/{data_product_id}/data-locations/qlik/app/app-layout-script:
    patch:
      summary: Update the qlik app layout script reference of a Data Product
      parameters:
        - name: data_product_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: qlik layout app script updated

  /storer/data-products/{data_product_id}/data-locations/apacheDrill/catalog-reference:
    patch:
      summary: Update the Apache Drill catalog reference of a Data Product
      parameters:
        - name: data_product_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Apache Drill catalog reference updated
  /storer/data-products/{data_product_id}/job:
    post:
      summary: Create a job for a Data Product
      parameters:
        - name: data_product_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Job created
  /storer/data-products/{data_product_id}/job/{job_id}:
    put:
      summary: Update a specific job information of a Data Product
      parameters:
        - name: data_product_id
          in: path
          required: true
          schema:
            type: string
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Job updated